### ISSUE TITLE
[Bug]: Finish all setups don't work

### ISSUE THREAD

**Issue by infinity-stack** [Deadlineem/Extras-Addon-for-YimMenu#126]
### Description

they don't work anymore like i would move the setups go down and up idk how to do It anymore

### Steps to Reproduce

Go to apartment heists
Go to pacific standard heist
Go to finish all setups
no work

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by USBMenus** [comment]
MPX was the issue, should be fixed now, also for further issues, please provide the error from the console if there is one

**Comment by Deadlineem** [comment]
> MPX was the issue, should be fixed now, also for further issues, please provide the error from the console if there is one

This ^ helps us determine issues easier.  Extras has over 10,000 lines of code lol

**Comment by infinity-stack** [comment]
I don't think it works

**Comment by Deadlineem** [comment]
> I don't think it works

@USBMenus i can try altering all MPX() to MPX regularly, that one worked idk if this function is proper or not.

**Comment by infinity-stack** [comment]
whole lotta scripting i don't know about

**Comment by USBMenus** [comment]
@Deadlineem its working with the function, i just tested it

**Comment by Deadlineem** [comment]
> @Deadlineem its working with the function, i just tested it

are you sure its with the function MPX()?  I just pushed an update to alter it to MPX .. instead, which is what everything else used before this change.

**Comment by USBMenus** [comment]
> are you sure its with the function MPX()? I just pushed an update to alter it to MPX .. instead, which is what everything else used before this change.

yep, didnt update to the latest commit yet

**Comment by Deadlineem** [comment]
> > are you sure its with the function MPX()? I just pushed an update to alter it to MPX .. instead, which is what everything else used before this change.
> 
> yep, didnt update to the latest commit yet

Ill revert it then, should be good to close this now and @infinity-stack update your Extras-Addon.lua AND your Extras-data.lua

**Comment by infinity-stack** [comment]
bruh

**Comment by USBMenus** [comment]
> bruh

you have to be doing something wrong if its still not working

**Comment by infinity-stack** [comment]
yes king

**Comment by infinity-stack** [comment]
Uploading Grand Theft Auto V 2024-08-11 00-08-15.mp4…

**Comment by infinity-stack** [comment]
https://github.com/user-attachments/assets/057a18e9-100e-41d1-a32f-8af093c6e0e1

**Comment by USBMenus** [comment]
did you update it?

**Comment by Deadlineem** [comment]
> did you update it?

I was experiencing this earlier as well with pacific standard tbh, i canceled the heist and retried and still does it.  @infinity-stack is this ONLY on Pacific standard?

**Comment by infinity-stack** [comment]
i sis

**Comment by infinity-stack** [comment]
i did

**Comment by infinity-stack** [comment]
> did you update it?

i did

**Comment by infinity-stack** [comment]
> > did you update it?
> 
> I was experiencing this earlier as well with pacific standard tbh, i canceled the heist and retried and still does it.
> 
> Did this before the MPX alterations
> 
> @infinity-stack is this ONLY on Pacific standard?

jesus I don't know I just made pacific standard heist

**Comment by Deadlineem** [comment]
> > > did you update it?
> > 
> > 
> > I was experiencing this earlier as well with pacific standard tbh, i canceled the heist and retried and still does it.
> > Did this before the MPX alterations
> > @infinity-stack is this ONLY on Pacific standard?
> 
> jesus I don't know I just made pacific standard heist

Call lester, cancel the heist and try redoing it with anything besides the pacific standard.

**Comment by infinity-stack** [comment]
ok

**Comment by infinity-stack** [comment]
na man it doesnt work

**Comment by infinity-stack** [comment]
i did fleeca and i know a way how to skip one setup and it don't work brah

**Comment by USBMenus** [comment]
> Call lester, cancel the heist and try redoing it with anything besides the pacific standard.

i did it with pacific earlier when i was testing it and it worked

**Comment by infinity-stack** [comment]
show me a video

**Comment by USBMenus** [comment]
> show me a video

Uploading skip.mp4…

**Comment by infinity-stack** [comment]
i didn't ask for the uploading lmao

**Comment by USBMenus** [comment]
> i didn't ask for the uploading lmao

my wifis sucks, updated it

**Comment by infinity-stack** [comment]
broo whatt

**Comment by Deadlineem** [comment]
> broo whatt
using MPX .. ( Not MPX() )
@USBMenus @infinity-stack 

I tested the apartment complete setups on Pacific Standard last night and it was working for me, although i generally have issues hosting heists so i dont do it often, it worked fine when i got it to actually go through.

**Comment by USBMenus** [comment]
> using MPX .. ( Not MPX() )
> @USBMenus @infinity-stack
> 
> I tested the apartment complete setups on Pacific Standard last night and it was working for me, although i generally have issues hosting heists so i dont do it often, it worked fine when i got it to actually go through.

if it works and you wanna change it go for it, it was working fine for me tho

**Comment by infinity-stack** [comment]
it makes my hair disappear
